"""Add pronouns column to users

Revision ID: 4c335c1ecd9d
Revises: a07e65c5cc1f
Create Date: 2025-04-09 06:26:23.055188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c335c1ecd9d'
down_revision = 'a07e65c5cc1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pronouns', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('pronouns')

    # ### end Alembic commands ###
