"""Add group_id column to user_plants

Revision ID: a07e65c5cc1f
Revises: 
Create Date: 2025-04-09 01:21:52.453956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a07e65c5cc1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_plants', schema=None) as batch_op:
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###
